name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, v18.16, '*']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build
      - run: npm test

      - run: zip -r webextension.zip public/*

      - uses: actions/upload-artifact@v4
        with:
          name: webextension
          path: webextension.zip
          if-no-files-found: error

      - name: Publish tagged release
        uses: svenstaro/upload-release-action@v2
        if: |
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/v') &&
          matrix.node-version == 'v18.16.0'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: webextension.zip
          file_glob: true
          tag: ${{ github.ref }}